### ISSUE TITLE
It works...but why?

### ISSUE THREAD

**Issue by robertodalmonte** [BRomeroT/GrpcServiceDemo#1]
Hello Benjamin,
first of all, THANK you for your sample. It works great, but I do not understand why (as per my ignorance).
On the console client-side, you declare the channel:
using var channel = GrpcChannel.ForAddress("https://localhost:5001"); (and I do understand)

On the Xamarin client-side that very same line won't work. What works is:using var channel = GrpcChannel.ForAddress("https://grpcservicedemo.azurewebsites.net/",
                new GrpcChannelOptions { HttpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler())) });
I do not understand...do you need an Azure account, is it a mandatory address in order for Xamarin to work, what on earth is going on....
Can you please explain or address me to some link, in order to redeem my ignorance?
How do I make it work with:
var channel = GrpcChannel.ForAddress("http://192.168.1.121:5001"); //my local server - intranet
Regards
Roberto Dalmonte

**Comment by Mrsevic** [comment]
The same issue of mine. Turns out that you could use your own dev certificate only if you use packages like grpc web or some similar. 

As for the http you should try with Grpc Core.

**Comment by robertodalmonte** [comment]
> 
> 
> The same issue of mine. Turns out that you could use your own dev certificate only if you use packages like grpc web or some similar.
> 
> As for the http you should Grpc Core.

Hello Mrsevic
did you manage to make Xamarin client connect to the server (one way or the other)? If yes can you post your solution?

**Comment by Mrsevic** [comment]
Will try to put out a sample on weekend.

**Comment by BRomeroT** [comment]
Hi, you don't need Azure, the Xamarin sample use my endpoint published in Azure.

You shuld have published your GRPC Service on any server private or public that your App could reach.
